trigger:
  - master

parameters:
  - name: deployMode
    displayName: 'Deployment Mode'
    type: string
    default: 'Normal'
    values:
      - Normal
      - Rollback
  - name: tag
    displayName: 'Tag to Rollback'
    type: string
    default: ' '

variables:
  - group: Terraform-SP
  - name: dockerComposePath
    value: /tmp/docker-compose
  - name: terraform_working_dir
    value: '$(System.DefaultWorkingDirectory)/iac'
  - name: application-name
    value: '$(Build.Repository.Name)'  
  - name: NUGET_PACKAGES
    value: $(Pipeline.Workspace)/.nuget/packages
  - name: DeployMode
    value: ${{ parameters.deployMode }}

pool:
    vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - script: |
        TRIMMED_TAG=$(echo "${{parameters.tag}}" | xargs)
        if [ -z "$TRIMMED_TAG" ]; then
          echo "##vso[task.logissue type=error]Tag parameter is required for Rollback mode"
          exit 1
        fi
        git remote set-url origin https://$(System.AccessToken)@dev.azure.com/$(System.TeamProject)/$(System.TeamProject)/_git/$(Build.Repository.Name)
        git fetch origin "refs/tags/$TRIMMED_TAG"
        git checkout FETCH_HEAD
        git describe --tags
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
      displayName: 'Checkout specific tag'
      condition: eq(variables['DeployMode'], 'Rollback')    
    - script: |
        if [ ! -d "$(NUGET_PACKAGES)" ]; then
          echo "Creating NuGet packages directory: $(NUGET_PACKAGES)"
          mkdir -p "$(NUGET_PACKAGES)"
        else
          echo "NuGet packages directory already exists: $(NUGET_PACKAGES)"
        fi
      displayName: 'Create NuGet Cache Directory'
    - task: Cache@2
      displayName: Cache NuGet packages
      inputs:
        key: 'nuget | "$(Agent.OS)" | src/*.csproj | tests/UnitTest/*.csproj'
        restoreKeys: |
          nuget | "$(Agent.OS)"
          nuget
        path: $(NUGET_PACKAGES)
    - task: UseDotNet@2
      displayName: Use DotNet 8
      inputs:
        packageType: 'sdk'
        version: '8.x'
    - task: DotNetCoreCLI@2
      displayName: DotNet Build
      inputs:
        command: 'build'
        projects: '$(System.DefaultWorkingDirectory)/**/*.sln'
        arguments: '--configuration Release /p:GenerateWorkerBindings=false'
    - task: DotNetCoreCLI@2
      displayName: 'DotNet Unit Tests'
      inputs:
        command: 'test'
        projects: 'tests/BigCommerce.Migration.UnitTests/BigCommerce.Migration.UnitTests.csproj tests/BigCommerce.Migration.OrchestrationTests/BigCommerce.Migration.OrchestrationTests.csproj'
        arguments: '--configuration Release --no-build --collect:"XPlat Code Coverage"'
        publishTestResults: true
    - task: PublishCodeCoverageResults@2
      displayName: 'Publish Code Coverage'
      inputs:
        summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'
    - task: DotNetCoreCLI@2
      displayName: 'DotNet Publish'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(System.DefaultWorkingDirectory)/src/*.csproj'
        arguments: '--configuration Release --output $(System.DefaultWorkingDirectory)/publish_output --no-build'
        zipAfterPublish: false
        modifyOutputPath: false
    - task: ArchiveFiles@2
      displayName: 'Archive'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop
      displayName: 'Publish Artifact'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:    
  - deployment: Deploy
    displayName: Deploy
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
            displayName: 'Checkout Repository'
            fetchDepth: 1
          - task: TerraformInstaller@1
            inputs:
              terraformVersion: '1.5.7'
          - script: |
              terraform init -backend-config="config_prod.azurerm.tfbackend" -backend-config="key=$(application-name).tfstate" -reconfigure
              terraform validate
              terraform plan -var-file="terraform.prod.tfvars" -var="function_app_name=$(application-name)" -out=tfplan
              terraform apply -auto-approve tfplan
            displayName: 'Terraform Init, Validate, Plan and Apply'
            workingDirectory: $(terraform_working_dir)
          - task: AzureFunctionApp@2
            displayName: 'Azure functions app deploy'
            inputs:
              connectedServiceNameARM: 'Azure Devops Service Connection'
              appType: functionApp
              appName: '$(application-name)'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              deploymentMethod: 'auto'

- stage: Git_Tag
  displayName: Create Deployment Tag
  condition: and(succeeded(), eq(variables['DeployMode'], 'Normal'))
  jobs:
  - job: TagDeployment
    displayName: Tag Successful Deployment
    steps:
    - checkout: self
      fetchDepth: 1
      persistCredentials: true
    - script: |
        git config user.name "Azure DevOps"
        git config user.email "devops@vortexiq.ai"
        git tag $(Build.BuildNumber)
        git push https://$(System.AccessToken)@dev.azure.com/vortexiq/VortexIQ/_git/$(Build.Repository.Name) $(Build.BuildNumber)
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)